variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

release-pypi:
  # 以开发镜像作为执行环境
  image: registry.fiblab.net/general/dev:latest
  stage: build
  only:
    - master
  script:
    - bash scripts/init.sh
    - pip3 install build -U
    - python3 -m build
    - |
      TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token \
      python3 -m twine upload --repository-url \
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*

build-docker-image:
  # default image of runner with tag dind
  # image: docker:dind
  tags:
    - dind
  stage: build
  only:
    - master
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA} -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker push ${CI_REGISTRY_IMAGE}:latest

kubernetes-deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  only:
    - master
  script:
    - kubectl config get-contexts
    - kubectl config use-context sim/kubernetes-agent:huawei
    - kubectl apply -f manifest.yaml
    - kubectl rollout restart deployment/pycitysim-doc-frontend --namespace web
