variables:
  # https://setuptools-git-versioning.readthedocs.io/en/stable/ci.html
  GIT_DEPTH: 0
  VERSION_REGEX: /^v\d+\.\d+\.\d+.*$/

stages:
  - build
  - deploy

release-pypi:
  # 以开发镜像作为执行环境
  image: registry.fiblab.net/general/dev:latest
  stage: build
  rules:
    - if: $CI_COMMIT_TAG =~ $VERSION_REGEX
  script:
    - pip3 install build setuptools-git-versioning -U
    - python3 -m build
    - |
      TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token \
      python3 -m twine upload --repository-url \
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*

build-docker-image:
  # default image of runner with tag dind
  # image: docker:dind
  tags:
    - dind
  stage: build
  rules:
    - if: $CI_COMMIT_TAG =~ $VERSION_REGEX
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    - docker push ${CI_REGISTRY_IMAGE}:latest
